### PR TITLE
Add page for London TWC

### PR DESCRIPTION
**Pull request by bobwhitelock**
As discussed in the `#local-uk-london` channel. If this all looks OK then please can you wait a day or two before merging, in case anyone in the channel wants to add anything. Thanks! :smile:

### CODE REVIEW

**Comment by bobwhitelock** [comment]
Is the CI failure a real issue? It says the following links 404:

```
- ./_site/it/london/index.html
  *  External link https://techworkerscoalition.org/it/london/ failed: 404 No error
- ./_site/london/index.html
  *  External link https://techworkerscoalition.org/london/ failed: 404 No error
- ./_site/ru/london/index.html
  *  External link https://techworkerscoalition.org/ru/london/ failed: 404 No error
```

But this is expected, as they're only being added in this PR.

**Comment by kidmillions** [comment]
No you are good, that's because the page doesn't exist until you've deployed it.

Sorry, the CI is new and we haven't worked out the kinks.

**Comment by bobwhitelock** [comment]
> No you are good, that's because the page doesn't exist until you've deployed it.
> 
> Sorry, the CI is new and we haven't worked out the kinks.

No worries, just thought I'd check I wasn't supposed to do anything to suppress these.

> Looks good, ping me when you want to release

I think we're good to go now, has been a couple of days and I've made one requested tweak, I can make a new PR if we need any other changes in future.

Thanks!

**Comment by shushugah** [comment]
I do have a request. This is for the home page, which is translated into multiple languages now. Which means Italian and Russian pages should be updated as well. For Italian you can do the exact the same thing, but for Russian `<a href="/london">Лондон</a>,`

**Comment by bobwhitelock** [comment]
Good point @shushugah, thanks for letting me know. Interesting that those are the current languages we have, when we don't have chapters there :slightly_smiling_face:.

I've made those changes now, if you want to check. For the Russian translation the current home page just has a list of place names rather than links, so I've just slotted 'London' in to that list rather than convert them all to links.

**Comment by shushugah** [comment]
We added Italian and Russian because they were native languages spoken by the largely migrant membership base of Berlin. Many chapters in tech have migrants, and the idea was to encourage/promote more languages. As it is a chicken/egg problem if we only promote content in English, we will only show up in English searches

**Comment by bobwhitelock** [comment]
@shushugah that's interesting, thanks for the explanation. And thanks for merging 🙂

**Pull request merged**
