### PR TITLE
Collective actions

### PR DESCRIPTION
**Pull request by shushugah**
This is a WIP, it shows the last 5 collective actions, along with their citations. I would love stylistic feedback/contributions, and missing still is an acknowledgment of this project. We could also create a sub domain, like techworkerscoalition.org/collective-actions which has longer list, and explanation of this project.

### CODE REVIEW

**Comment by rossPatton** [comment]
any chance you could include a screenshot of what it looks like?

**Comment by rossPatton** [comment]
nvm, just ran it locally myself. only feedback i have is i'd add a little margin-bottom between each entry

Screen Shot 2020-05-02 at 5 35 37 PM

**Comment by kidmillions** [comment]
This is good content, but I think we should keep it simple on the front page, and move this to another page, as you suggested.

**Comment by shushugah** [comment]
> any chance you could include a screenshot of what it looks like?

A preview of these changes are available here: https://deploy-preview-213--techworkerscoalition.netlify.app/ (see the bottom of this PR, for the preview link)

**Comment by shushugah** [comment]
> This is good content, but I think we should keep it simple on the front page, and move this to another page, as you suggested.
> 
> I also don't think it's a good idea to read content from external json and display it on our site. Seems like a vector for content which we can't really control to make it onto our front page without our input. I understand that the json is maintained by friends of TWC, but it makes me nervous.

how is it any different from us rendering calendar events from external google calendars on /nyc page? One additional thing I can do, is load a default copy of JSON, in case the website is down for whatever reason, and also sanitize any input

**Comment by kidmillions** [comment]
I guess the difference would be that presumably only TWC volunteers are editing the calendars, while this json snippet includes contributors who may not necessarily be TWC volunteers. I see your point, though, and I don't think there's a need to sanitize. I would just argue that this may not be front page content.

**Comment by shushugah** [comment]
In general, I think we ought to have more moving content on our first page, like upcoming events, recent newsletters, etc... because lot of movement pages look active but are dormant, and this can show we're bubbling with activity.

**Comment by rossPatton** [comment]
should we merge this ?

**Comment by rossPatton** [comment]
since 2 of us have approved, i'll just go ahead and merge

**Pull request merged**
