### PR TITLE
Start on reworking TWC site

### PR DESCRIPTION
**Pull request by rossPatton**
Hey so, I might be over-stepping my bounds but I want to try and address a number of issues re: the website.

1 - replaced language block and "Learn"/"Connect" links with simple drop down navs. this'll make it easier for us to add more languages in the future, and more sub pages. it also helps pull the page up a bit
2 - simplify styling by a lot. goal here is to have a site that is clearly mobile first and is performant. i can go back later and try to make it more appealing aesthetically
3 - Removed learning club link (can add back later?) page doesnt seem active, no indication of how to sign up, etc
4 - added a CSP and some mild link protection. it's a static site, so, not exactly a whole lot of harm can be done, but it doesn't hurt to add a little bit of security. i would be interested to know more about the hosting situation, we score pretty badly on the security front

obviously, open to feedback here, just want to get this PR up now so it's on folk's radar. 

future ideas could incude:
- a more serious style and design pass, possibly bring in a real designer?
- implement a consistent css framework. i like tailwind
- split stuff off into more sub pages. chapters for instance. could cut some homepage content and move to an expanded about page? could also split up the collective actions list. for instance, have the 3 most recent on the homepage, and on a sub-page pull the 10 most recent with a link back to the collective action website?

### CODE REVIEW

**Comment by rossPatton** [comment]
also, as far as i can gather, is the site being served from s3, and the form submit from heroku?

i have nothing against heroku, but if we are using s3, we should consider an alternative service. there has to be some hosting platform that can accommodate static site hosting that isn't run by amazon

**Comment by shushugah** [comment]
I'd be a huge fan of serving the website over Netlify, which is what `techworkersberlin.com` uses. I tell it to run `jekyll serve` and it otherwise already installs all gems locally etc..

**Comment by simonv3** [comment]
Looks good, I like simpler.

My main suggestion is giving the header and the sub-header a bit more space:

image

maybe like so:

image

**Comment by rossPatton** [comment]
well i'm not opposed to opening up the spacing a bit, but perhaps not that much? happy to meet in the middle somewhere

anyone else have any issues i should address before approval?

also @shushugah yeah, i was thinking netlify myself as well

**Comment by shushugah** [comment]
I have some thoughts about the footer (it shouldn't be vertically stacked in desktop mode) etc, but in short this PR moves us forward and I'd be happy to implement a new PR with more tweaks, as we get feedback from more users! 

What you did with the languages was absolutely clean and wonderful! Let's ship this this!

**Comment by rossPatton** [comment]
cool. sometime tonight then i'll address the spacing comment and horizontally align the links on desktop, and then i'll merge barring no other objections? assumption being we will continue to iterate

**Comment by rossPatton** [comment]
so i added a little bit more space at the top and made the links horizontal. could I get an approval @kidmillions @shushugah ?

Plan on continuing to iterate, so long as folks are okay with that

**Comment by kidmillions** [comment]
The AWS/netlify discussion should move elsewhere, but yes this site is currently on s3. We also use other AWS services like cloudfront and route 53.

**Comment by rossPatton** [comment]
Sure, maybe just move all the links to the footer and add a blurb about the newsletter/slack on the homepage, would that work? 

It does free up some space in the header for another idea I had though, which would be to have a menu for all the chapters instead of just listing them out in the text on the homepage only.

also, let's make an issue w/r/t the hosting situation?

as for the header text thing, that's how it is now actually, so i left it. if we want to change, i'm happy to make the header just a little bit smaller on mobile so it'll fit

**Comment by rossPatton** [comment]
@kidmillions those comments should be addressed, and i've added a chapter menu, which i think will be pretty useful. especially if we continue to add chapters

**Comment by shushugah** [comment]
If anyone wants to review this PR locally, (because this a forked branch PR) they can run this command `git fetch origin pull/219/head:pr/219 && git checkout pr/219` (219 corresponds with the PR number)

I am very happy with the changes made here. I have two last small things, but we can also do them as a separate PR. 

1. In Italian and Russian, the word "worker" should also be highlighted in red, ie `рабочих` and `lavoratori`
2. The collective actions snippet should only be rendered in English, which can be fixed by changing index.md to 
```liquid
{% if site.lang == 'en' %}
  {% include collective-actions.html %}
{% endif %} 
```

**Comment by rossPatton** [comment]
hey, i'll go ahead and just make those comments since it seems like the ci checks here are stuck anyway

**Comment by rossPatton** [comment]
@shushugah just FYI, those issues should be fixed.

i also added a white bg to the favicon. the current one looks broken when you use a browser in night mode since it's transparent. basically, the "W" disappears

**Comment by rossPatton** [comment]
i would like to merge and deploy, if folks are cool with that. don't want to surprise folks with an unannounced weekend deploy

**Comment by rossPatton** [comment]
just a bump on this. i think we're good to merge but looks like the CI checks stalled again? @kidmillions @shushugah

**Pull request merged**
